### ISSUE TITLE
TFM application missing

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/STM32CubeU5#36]
Why TFM application available in `STM32Cube_FW_U5_V1.4.0.zip` package did not make it to `Projects/B-U585I-IOT02A/Applications` ?

**Comment by ALABSTM** [comment]
Hi @tdjastrzebski,

Actually this application has been removed as indicated in the [README.md](https://github.com/STMicroelectronics/STM32CubeU5?tab=readme-ov-file#some-middleware-libraries-and-projects-are-unavailable-in-this-repository) file. This is due to licensing aspects preventing from exposing it on GitHub. More details can be found in [this](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions/17) post.

I hope this answers your question. Please allow me to close this thread.

With regards,
