### ISSUE TITLE
TFM Application does not build

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/STM32CubeU5#37]
TFM Application does not build. According to the `readme.html` found in TFM application root folder:

_In order to build the TFM_Appli Secure and Non Secure projects, you must do the following:
• Open your preferred toolchain
• Rebuild the two projects_

I have tried, but:
1. Application does not build. All build did was it created lots of **yaml** (!?) files.
2. Solution structure does not resemble the one documented in [UM2851 - Getting started with STM32CubeU5 TFM application](https://www.st.com/resource/en/user_manual/dm00778528-.pdf), page 33 - screenshot below

Was this app actually tested before publishing?
CubeMX and CubeIDE are the latest version

Please advise.

<img width="728" alt="TFM1" src="https://github.com/STMicroelectronics/STM32CubeU5/assets/7325277/856f1095-d67e-4682-99e5-bce9e267d50d">

<img width="767" alt="image" src="https://github.com/STMicroelectronics/STM32CubeU5/assets/7325277/8479ac3f-9b0c-4660-8d76-58e41744e013">

<img width="767" alt="image" src="https://github.com/STMicroelectronics/STM32CubeU5/assets/7325277/73d8c426-9c53-4377-a0f2-574acea6bc6f">

**Comment by RJMSTM** [comment]
Hello,

Actually this application has been removed as indicated in the [README.md](https://github.com/STMicroelectronics/STM32CubeU5?tab=readme-ov-file#some-middleware-libraries-and-projects-are-unavailable-in-this-repository) file. This is due to licensing aspects preventing from exposing it on GitHub and  now is out of the scope of our GitHub' activity. They are rather treated at [ST Community](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus) level. Please allow me to redirect you to post your request in the adequate topic from [this](https://community.st.com/s/topiccatalog) list.

Now, as this issue is not directly related to some software published in GitHub, please allow me to close it.

More details can be found in https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions/17 post.

Thank you for your comprehension. We are looking forward to reading from you again.

With regards,

**Comment by RJMSTM** [comment]
Hello @tdjastrzebski ,

Actually this application has been removed as indicated in the [README.md](https://github.com/STMicroelectronics/STM32CubeU5?tab=readme-ov-file#some-middleware-libraries-and-projects-are-unavailable-in-this-repository) file. This is due to licensing aspects preventing from exposing it on GitHub and now is out of the scope of our GitHub' activity. They are rather treated at [ST Community](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus) level. Please allow me to redirect you to post your request in the adequate topic from [this](https://community.st.com/s/topiccatalog) list.

Now, as this issue is not directly related to some software published in GitHub, please allow me to close it.

More details can be found in https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions/17 post.

Thank you for your comprehension. We are looking forward to reading from you again.

With regards,
